### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing 

### ISSUE THREAD

**Issue by EddyTheCo** [dlt-green/node-installer-docker#386]
When using the browser to do API requests to the Hornet [Core](https://github.com/iotaledger/tips/blob/main/tips/TIP-0025/tip-0025.md) and [Indexer](https://github.com/iotaledger/tips/blob/main/tips/TIP-0026/tip-0026.md)  REST API to nodes installed by this installer, the API request is denied.
The reason given by the browser is  ‘Reason: CORS header ‘Access-Control-Allow-Origin’ missing’. 
One can see an example of this [here](https://eddytheco.github.io/NftMinter/).
In that case, one needs to set the Access-Control-Allow-Origin header’s value as explained [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin).

In my opinion, the nodes installed by this installer should respond to browser requests by default.
For this one needs to add
```
- "traefik.http.middlewares.cors.headers.customResponseHeaders.Access-Control-Allow-Origin=*"
- "traefik.http.routers.hornet.middlewares=cors"
```
to `docker-compose.yml` of the Hornet nodes.

Then every node maintainer is free to deny API requests from the browser, maybe by configuration variable of the installer or just deleting the lines we added. 

I could do a PR with the need changes if you consider this is need it.
Best,
Eduardo.

**Comment by dlt-green** [comment]
Hy Eduardo
It's possible that you make a PR to our dev branch - we will check it
