### ISSUE TITLE
Update video tutorials

### ISSUE THREAD

**Issue by JannemanDev** [dlt-green/node-installer-docker#398]
Suggestion to put on the backlog:
The video tutorials on Youtube are quite old mainly because node installer has been developed so fast last year so thats a good thing :)
I suggest it also contains how to register to become a pool member, add pool id to TXT record etc. All steps (still complete and correct btw?) mentioned in https://dlt.green/registrierung

**Comment by dlt-green** [comment]
### installation video:
this has no prio, maybe make one? ;-)

### this has nothing todo with our installer and is no issue:
I suggest it also contains how to register to become a pool member, add pool id to TXT record etc. All steps (still complete and correct btw?) mentioned in https://dlt.green/registrierung

**Comment by dlt-green** [comment]
no support received
