### ISSUE TITLE
reboot maintenance

### ISSUE THREAD

**Issue by dlt-green** [dlt-green/node-installer-docker#401]
it would be nice, if the system will only rebooted if needed

**Comment by 0xKtota** [comment]
A simple check for the existence of the file would be sufficient
```
if [ -f /var/run/reboot-required ]; then
  sudo reboot
fi
```

**Comment by dlt-green** [comment]
I already know this for Ubuntu, but have to check if it also works with Debian... its already planned in this direction...

**Comment by dlt-green** [comment]
> A simple check for the existence of the file would be sufficient
> 
> ```
> if [ -f /var/run/reboot-required ]; then
>   sudo reboot
> fi
> ```

this will also work on debian, will be implemented as suggested. think it also would be good then to bring an info message, that no reboot is required, because a reboot is forced with a flag. then it means, that you set the flag for reboot, and the reboot will only be made when necessary. must be also updated in readme (what is no problem), but i think it would be nice to implement this on that way.

**Comment by dlt-green** [comment]
please see above, i think it would be good solution on this way, if someone has additionally some input please comment or check my message.

**Comment by dlt-green** [comment]
**ℹ️can already be tested in dev**

**Comment by dlt-green** [comment]
https://ubuntuforums.org/showthread.php?t=2475383

**Comment by dlt-green** [comment]
there are maybe some problems reported (further testing necessary)
