### ISSUE TITLE
Hash error on Iota Nova Wasp install

### ISSUE THREAD

**Issue by kaktus2** [dlt-green/node-installer-docker#439]
The package download of the iota 2.0 wasp install seems be corrupted, or the value of the hash is wrong

<img width="652" alt="Screenshot 2024-05-22 100039" src="https://github.com/dlt-green/node-installer-docker/assets/2196583/3b6caf47-8f32-4f0c-8917-0d701779facf">

**Comment by dlt-green** [comment]
Hy. Iota 2.0 wasp you cant install in the moment, you can only install the iota core node. This is no Bug.

**Comment by dlt-green** [comment]
We will temporarily deactivate the option :-). thanks

**Comment by dlt-green** [comment]
solved:
![image](https://github.com/dlt-green/node-installer-docker/assets/89119285/120888e1-d153-4638-860a-de1a44f8b151)
