### ISSUE TITLE
JWT generation for nova-iotacore searching for hornet service

### ISSUE THREAD

**Issue by kaktus2** [dlt-green/node-installer-docker#440]
JWT generation for nova-iotacore is searching for hornet service,
I think it should be the nova-iotacore service :)

<img width="502" alt="new" src="https://github.com/dlt-green/node-installer-docker/assets/2196583/1011519b-7969-4aa4-8594-bdb7425e4a05">

**Comment by dlt-green** [comment]
should work now, please test and confirm

**Comment by kaktus2** [comment]
> should work now, please test and confirm

works like a charm now, thx
